# Generated by Django 3.1.2 on 2020-10-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=2083)),
                ('contact_num', models.CharField(max_length=15, validators=[resume.models.validate_num])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
