# Generated by Django 3.1.2 on 2020-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201116_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelog',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profilelog',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profilelog',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
