# Generated by Django 3.1.2 on 2020-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201116_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_updated',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='profilelog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=283, null=True),
        ),
    ]
