# Generated by Django 3.1.2 on 2020-11-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201116_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogpost',
        ),
    ]
