# Generated by Django 3.1.2 on 2020-11-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201116_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogpost',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.blogpost'),
        ),
    ]
