# Generated by Django 3.1.2 on 2020-10-19 16:10

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_num',
            field=models.CharField(max_length=17, validators=[resume.models.validate_num]),
        ),
    ]
