# Generated by Django 3.1.2 on 2020-10-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0003_auto_20201019_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('github', 'GITHUB'), ('facebook', 'FACEBOOK'), ('youtube', 'YOUTUBE'), ('instagram', 'INSTAGRAM'), ('linkedin', 'LINKEDIN'), ('twitter', 'TWITTER'), ('website', 'WEBSITE')], default='facebook', max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_social', to=settings.AUTH_USER_MODEL),
        ),
    ]
