# Generated by Django 3.1.2 on 2020-10-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20201020_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='position',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='position',
        ),
    ]
