# Generated by Django 3.1.2 on 2020-10-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201020_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
    ]
