# Generated by Django 3.1.2 on 2020-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_interest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
