# Generated by Django 3.1.2 on 2020-10-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20201020_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
