# Generated by Django 3.1.2 on 2020-10-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
