# Generated by Django 3.1.2 on 2020-10-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20201023_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
