# Generated by Django 3.1.2 on 2020-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_workflow_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_num',
            field=models.BooleanField(default=False),
        ),
    ]
