# Generated by Django 3.1.2 on 2020-10-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20201023_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
    ]
