# Generated by Django 3.1.2 on 2020-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_auto_20201023_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
