# Generated by Django 3.1.2 on 2020-10-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_auto_20201024_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favicon_pic',
            new_name='favicon',
        ),
    ]
