# Generated by Django 3.1.2 on 2020-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(max_length=283),
        ),
    ]
