# Generated by Django 3.1.2 on 2020-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_auto_20201025_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(),
        ),
    ]
